### ISSUE TITLE
issue with 0 files in subfolders of train2014

### ISSUE THREAD

**Issue by gateway** [ThomasDougherty/pytorch-video-style-transfer#1]
Hi, I'm testing out this package on my ubuntu 18.x with a nvidia 1080.. I have downloaded all sets and put them in a coco folder in the root of the project for now.. however when I try to train the model is fails with this output.

```
(base) gateway@gateway-media:~/work/video/pytorch-video-style-transfer$ python main.py train --dataset /home/gateway/work/video/pytorch-video-style-transfer/coco/train2014/ --style-image /home/gateway/work/styles/r.jpg  --save-model-dir /home/gateway/work/video/pytorch-video-style-transfer/models/ --cuda 1
Starting train...
Traceback (most recent call last):
  File "main.py", line 91, in <module>
    main()
  File "main.py", line 84, in main
    train(args)
  File "/home/gateway/work/video/pytorch-video-style-transfer/engine.py", line 31, in train
    train_dataset = datasets.ImageFolder(args.dataset, transform)
  File "/home/gateway/anaconda3/lib/python3.7/site-packages/torchvision/datasets/folder.py", line 209, in __init__
    is_valid_file=is_valid_file)
  File "/home/gateway/anaconda3/lib/python3.7/site-packages/torchvision/datasets/folder.py", line 97, in __init__
    "Supported extensions are: " + ",".join(extensions)))
RuntimeError: Found 0 files in subfolders of: /home/gateway/work/video/pytorch-video-style-transfer/coco/train2014/
Supported extensions are: .jpg,.jpeg,.png,.ppm,.bmp,.pgm,.tif,.tiff,.webp
(base) gateway@gateway-media:~/work/video/pytorch-video-style-transfer$ ls -la coco/
total 6916
drwxrwxr-x 5 gateway gateway    4096 Sep 25 12:29 .
drwxrwxr-x 8 gateway gateway    4096 Sep 25 13:29 ..
drwxrwxr-x 2 gateway gateway    4096 Sep 25 12:20 annotations
drwxrwxr-x 2 gateway gateway 4751360 Aug 15  2014 train2014
drwxrwxr-x 2 gateway gateway 2314240 Aug 15  2014 val2014
(base) gateway@gateway-media:~/work/video/pytorch-video-style-transfer$ ls -la coco/train2014/
total 13346564
drwxrwxr-x 2 gateway gateway 4751360 Aug 15  2014 .
drwxrwxr-x 5 gateway gateway    4096 Sep 25 12:29 ..
-rw-rw-r-- 1 gateway gateway  224297 Aug 15  2014 COCO_train2014_000000000009.jpg

```

any ideas on this?

**Comment by gateway** [comment]
hmm seems like this solution worked.. which is odd.. 

https://stackoverflow.com/questions/54613573/runtimeerror-found-0-files-in-subfolders-of-error-about-subfolder-in-pytor

> I met the same problem when using celebA, including 200,000 images. As we can see there are many images. But in a small sample situation (I tried 20 images), I checked, the error will not be raised, which means we can read images successfully. But when the number grows, we should use other methods.
> 
> I solved the problem according to this website. Thanks to QimingChen Github solution
> 
> Simply, adding another folder named 1 (/train/--->train/1/) in the original folder will enable our program to work, without changing the path. That's because when facing large datasets, images should be sorted in subfolders of different classes.
> 
> The Original answer on Github:
> 
> Let's say I am going to use ImageFolder("/train/") to read jpg files in folder train. The file structure is /train/ -- 1.jpg -- 2.jpg -- 3.jpg
> 
> I failed to load them, leading to errors: RuntimeError: Found 0 images in subfolders of: ./data Supported image extensions are: .jpg,.JPG,.jpeg,.JPEG,.png,.PNG,.ppm,.PPM,.bmp,.BMP
> 
> I read the solution above and tried tens of times. When I changed the structure to /train/1/
> 
> -- 1.jpg -- 2.jpg -- 3.jpg
> 
> But the read in code is still -- ImageFolder("/train/"), IT WORKS.
> 
> It seems like the program tends to recursively read in files, that is convenient in some cases.
> 
> Hope this would help!!

**Comment by ThomasDougherty** [comment]
@gateway thank you for bringing this up. Didn't realized that I actually changed my folder to _./train2014/train2014_ to avoid this issue. I'll start working on the dataloading so you can keep the path pointing directly to the train2014 image folder. Will reply back shortly!

**Comment by ThomasDougherty** [comment]
@gateway fixed the dataloading so you can keep the path directed at train2014. Let me know if there's any additional issues! Will be closing this thread.
